[defaults]
name = "Tim Slim"
email = "timslim@climate-resource.com"
dataset_name = "example"
dataset_name_human = "Example Dataset"
dataset_description = "Test project made with copier-template-tester"
project_url = "https://github.com/climate-resource/ctt-project"

[output."tests/regression/ctt/defaults"]
