[project]
name = "copier-bookshelf-dataset"
version = "0.2.2a1"
description = "Copier template for a bookshelf dataset"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[tool.uv]
dev-dependencies = [
    "copier-template-tester>=2.1.3",
    "pytest>=8.3.3",
    "toml>=0.10.2",
]
