[project]
name = "copier-bookshelf-dataset"
version = "0.2.5a1"
description = "Copier template for a bookshelf dataset"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "copier-template-tester>=2.5.0",
    "pytest>=8.3.3",
    "towncrier>=25.8.0",
]
