[tool.towncrier]
# This runs towncrier in non-python mode, so we need to specify the project name and version at run-time
name = "copier-bookshelf-dataset"
filename = "CHANGELOG.md"
directory = "changelog/"
title_format = "## copier-bookshelf-dataset {version} ({project_date})"
underlines = [
    "",
    "",
    "",
]
issue_format = "[#{issue}](https://github.com/climate-resource/copier-bookshelf-dataset/pull/{issue})"
type = [
    { directory = "breaking", name = "Breaking Changes", showcontent = true },
    { directory = "deprecation", name = "Deprecations", showcontent = true },
    { directory = "feature", name = "Features", showcontent = true },
    { directory = "improvement", name = "Improvements", showcontent = true },
    { directory = "fix", name = "Bug Fixes", showcontent = true },
    { directory = "docs", name = "Improved Documentation", showcontent = true },
    { directory = "trivial", name = "Trivial/Internal Changes", showcontent = false },
]
